spring:
  datasource:
    url: jdbc:h2:mem:emotiondb;MODE=LEGACY;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        jdbc:
          time_zone: Asia/Seoul
    open-in-view: false
    defer-datasource-initialization: true
  h2:
    console:
      enabled: true
      path: /h2-console
  sql:
    init:
      mode: always

server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: health



logging:
  level:
    org.hibernate.SQL: warn


